spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.25.75.77:3306/vispro?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: vispro
    password: 1111
  #邮箱基本配置
  mail:
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994

    host: smtp.qq.com
    #发送者邮箱
    username: 1873046620@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: xncoacfoxovebibi
    #端口号465或587
    port: 465
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: true
            #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
            required: true
        debug: true



#百度OCR配置
bd:
  config:
    ocr-app-id: 115931857
    ocr-api-key: BOO6FZfMEi99JHuODCoMRXqw
    ocr-secret-key: qn35fWbmx0gc9cG7qdXs6pnLKrdMfAZN
    enhance-app-id: 116094898
    enhance-api-key: 5g2YQVPEHTyrtHi54wzCWL5g
    enhance-secret-key: QjVqipr6OYnpI6AlwViAuiPFbWcXR1pP



