server:
  port: 8080
  address: 0.0.0.0                  # 监听所有 IP 地址




spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.25.75.77:3306/vispro?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: vispro
    password: 1111



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false    # 开启驼峰命名
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cosmos.usercenter.pojo   # 实体扫描，多个package用逗号或者分号分隔
  global-config:
    db-config: #配置查找的时候的逻辑删除，如果存在逻辑被删除的信息，就默认不查询
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值




#百度OCR配置
bd:
  config:
    ocr-app-id: 115931857
    ocr-api-key: BOO6FZfMEi99JHuODCoMRXqw
    ocr-secret-key: qn35fWbmx0gc9cG7qdXs6pnLKrdMfAZN

    enhance-app-id: 116094898
    enhance-api-key: 5g2YQVPEHTyrtHi54wzCWL5g
    enhance-secret-key: QjVqipr6OYnpI6AlwViAuiPFbWcXR1pP